version: "2"
services:
  node:
    build: "."
    image: "rdm-webdav-proxy"
    volumes:
      - ./config:/user/src/app/config
      - ./log:/user/src/app/log
      - ./ssl:/user/src/app/ssl
    ports:
      - "3000:3000"
